name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://debk1q95drmes1rd5o4q7ibfb616m3vpbodkahta2v3p3rhtpt2fua3l.qc.dolfincdnx.net:24660/xdispatch248f46eb6f1f704e/bigota.d.miui.com/20.6.17/miui_MI6X_20.6.17_f4bf514fcf_9.0.zip?BSLuBan=eyJob3N0IjoiYmlnb3RhLmQubWl1aS5jb20iLCJic3JlcWlkIjoiYmJkZmU2YmEzMWYzNmIzZjEzNzE3Y2YyMmFmYjU1YmQiLCJjYWNoZV9rZXkiOiJcLzIwLjYuMTdcL21pdWlfTUk2WF8yMC42LjE3X2Y0YmY1MTRmY2ZfOS4wLnppcCIsImRuc19ob3N0IjoicGYwMDMudi5ic2dzbGIuY24iLCJrZXkiOiJjZWZlYzA0MjJjODZmNmE0OTJiOGZkZDEyOTA1MTYzOSIsInRzIjoxNjkxNTczOTgxfQ==
  ROM_NAME: MIUI
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
